### Crear un nuevo producto
@BASE_URL = http://localhost:3050/api
@productId = 6827a020fb2f9a649f1d4be6

POST {{BASE_URL}}/products
Content-Type: application/json

{
    "name": "El Principito",
    "price": 2500,
    "description": "Libro clásico de Antoine de Saint-Exupéry",
    "stock": 50,
    "category": "libro",
    "prueba": "prueba"
}

### Obtener todos los productos
GET {{BASE_URL}}/products

### Obtener un producto por ID
GET {{BASE_URL}}/products/6827a020fb2f9a649f1d4be6

### Actualizar un producto
PUT {{BASE_URL}}/products/6827a020fb2f9a649f1d4be6
Content-Type: application/json

{
    "name": "El Principito 2",
    "price": 2800,
    "description": "Libro clásico de Antoine de Saint-Exupéry - Edición especial",
    "stock": 45,
    "category": "libro"
}

### Eliminar un producto
DELETE {{BASE_URL}}/products/{{productId}}
